# $Id$

include ../config.mk
-include ../config-local.mk

DOCDIR = $(LIBDIR)/webdoc/invenio/help/

all:
	@echo "Done."

test:
	@echo "Nothing to test."

install:
	@echo "Done."

clean:
	@rm -f *.orig *~

# end of file
